<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RAIAANs-Air.fios-router.home" failures="1" tests="3" name="org.suborg.project.teamname.runner.CucumberTestRunner" time="11.258" errors="0" timestamp="2020-08-16T15:20:05 EDT" skipped="0">
  <testcase classname="org.suborg.project.teamname.runner.CucumberTestRunner" name="runScenario" time="1.377"/>
  <system-out/>
  <testcase classname="org.suborg.project.teamname.runner.CucumberTestRunner" name="runScenario" time="9.009">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at org.suborg.project.teamname.stepdefinition.DemoFeature1Step.yet_another_action(DemoFeature1Step.java:52)
at âœ½._1df1 yet another action(file:///Users/smr1/Documents/AutomationTemplatePersonal/project/test-framework-template/src/test/resources/features/DemoFeature1.feature:29)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="org.suborg.project.teamname.runner.CucumberTestRunner" name="runScenario" time="0.872"/>
  <system-out/>
</testsuite> <!-- org.suborg.project.teamname.runner.CucumberTestRunner -->
